"""迁移脚本

Revision ID: 1f6d6722d45b
Revises: 
Create Date: 2026-01-13 23:44:47.122291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6d6722d45b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('order', sa.Integer(), nullable=False, comment='显示排序'),
    sa.Column('code', sa.String(length=16), nullable=True, comment='部门编码'),
    sa.Column('leader', sa.String(length=32), nullable=True, comment='部门负责人'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机'),
    sa.Column('email', sa.String(length=64), nullable=True, comment='邮箱'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级部门ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_dept.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='部门表'
    )
    op.create_index(op.f('ix_sys_dept_code'), 'sys_dept', ['code'], unique=False)
    op.create_index(op.f('ix_sys_dept_created_id'), 'sys_dept', ['created_id'], unique=False)
    op.create_index(op.f('ix_sys_dept_created_time'), 'sys_dept', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_dept_id'), 'sys_dept', ['id'], unique=False)
    op.create_index(op.f('ix_sys_dept_parent_id'), 'sys_dept', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_dept_status'), 'sys_dept', ['status'], unique=False)
    op.create_index(op.f('ix_sys_dept_updated_id'), 'sys_dept', ['updated_id'], unique=False)
    op.create_index(op.f('ix_sys_dept_updated_time'), 'sys_dept', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_dept_uuid'), 'sys_dept', ['uuid'], unique=True)
    op.create_table('sys_dict_type',
    sa.Column('dict_name', sa.String(length=64), nullable=False, comment='字典名称'),
    sa.Column('dict_type', sa.String(length=255), nullable=False, comment='字典类型'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_type'),
    comment='字典类型表'
    )
    op.create_index(op.f('ix_sys_dict_type_created_time'), 'sys_dict_type', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_id'), 'sys_dict_type', ['id'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_status'), 'sys_dict_type', ['status'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_updated_time'), 'sys_dict_type', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_uuid'), 'sys_dict_type', ['uuid'], unique=True)
    op.create_table('sys_menu',
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单名称'),
    sa.Column('type', sa.Integer(), nullable=False, comment='菜单类型(1:目录 2:菜单 3:按钮/权限 4:链接)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='显示排序'),
    sa.Column('permission', sa.String(length=100), nullable=True, comment='权限标识(如:module_system:user:query)'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='菜单图标'),
    sa.Column('route_name', sa.String(length=100), nullable=True, comment='路由名称'),
    sa.Column('route_path', sa.String(length=200), nullable=True, comment='路由路径'),
    sa.Column('component_path', sa.String(length=200), nullable=True, comment='组件路径'),
    sa.Column('redirect', sa.String(length=200), nullable=True, comment='重定向地址'),
    sa.Column('hidden', sa.Boolean(), nullable=False, comment='是否隐藏(True:隐藏 False:显示)'),
    sa.Column('keep_alive', sa.Boolean(), nullable=False, comment='是否缓存(True:是 False:否)'),
    sa.Column('always_show', sa.Boolean(), nullable=False, comment='是否始终显示(True:是 False:否)'),
    sa.Column('title', sa.String(length=50), nullable=True, comment='菜单标题'),
    sa.Column('params', sa.JSON(), nullable=True, comment='路由参数(JSON对象)'),
    sa.Column('affix', sa.Boolean(), nullable=False, comment='是否固定标签页(True:是 False:否)'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_menu.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表'
    )
    op.create_index(op.f('ix_sys_menu_created_time'), 'sys_menu', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_menu_id'), 'sys_menu', ['id'], unique=False)
    op.create_index(op.f('ix_sys_menu_parent_id'), 'sys_menu', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_menu_status'), 'sys_menu', ['status'], unique=False)
    op.create_index(op.f('ix_sys_menu_updated_time'), 'sys_menu', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_menu_uuid'), 'sys_menu', ['uuid'], unique=True)
    op.create_table('sys_param',
    sa.Column('config_name', sa.String(length=64), nullable=False, comment='参数名称'),
    sa.Column('config_key', sa.String(length=500), nullable=False, comment='参数键名'),
    sa.Column('config_value', sa.String(length=500), nullable=True, comment='参数键值'),
    sa.Column('config_type', sa.Boolean(), nullable=True, comment='系统内置(True:是 False:否)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统参数表'
    )
    op.create_index(op.f('ix_sys_param_created_time'), 'sys_param', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_param_id'), 'sys_param', ['id'], unique=False)
    op.create_index(op.f('ix_sys_param_status'), 'sys_param', ['status'], unique=False)
    op.create_index(op.f('ix_sys_param_updated_time'), 'sys_param', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_param_uuid'), 'sys_param', ['uuid'], unique=True)
    op.create_table('sys_role',
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=16), nullable=True, comment='角色编码'),
    sa.Column('order', sa.Integer(), nullable=False, comment='显示排序'),
    sa.Column('data_scope', sa.Integer(), nullable=False, comment='数据权限范围(1:仅本人 2:本部门 3:本部门及以下 4:全部 5:自定义)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_index(op.f('ix_sys_role_code'), 'sys_role', ['code'], unique=False)
    op.create_index(op.f('ix_sys_role_created_time'), 'sys_role', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=False)
    op.create_index(op.f('ix_sys_role_status'), 'sys_role', ['status'], unique=False)
    op.create_index(op.f('ix_sys_role_updated_time'), 'sys_role', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_role_uuid'), 'sys_role', ['uuid'], unique=True)
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名/登录账号'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='昵称'),
    sa.Column('mobile', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=64), nullable=True, comment='邮箱'),
    sa.Column('gender', sa.String(length=1), nullable=True, comment='性别(0:男 1:女 2:未知)'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL地址'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超管'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('gitee_login', sa.String(length=32), nullable=True, comment='Gitee登录'),
    sa.Column('github_login', sa.String(length=32), nullable=True, comment='Github登录'),
    sa.Column('wx_login', sa.String(length=32), nullable=True, comment='微信登录'),
    sa.Column('qq_login', sa.String(length=32), nullable=True, comment='QQ登录'),
    sa.Column('dept_id', sa.Integer(), nullable=True, comment='部门ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username'),
    comment='用户表'
    )
    op.create_index(op.f('ix_sys_user_created_id'), 'sys_user', ['created_id'], unique=False)
    op.create_index(op.f('ix_sys_user_created_time'), 'sys_user', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_user_dept_id'), 'sys_user', ['dept_id'], unique=False)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_index(op.f('ix_sys_user_updated_id'), 'sys_user', ['updated_id'], unique=False)
    op.create_index(op.f('ix_sys_user_updated_time'), 'sys_user', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_user_uuid'), 'sys_user', ['uuid'], unique=True)
    op.create_table('app_ai_mcp',
    sa.Column('name', sa.String(length=50), nullable=False, comment='MCP 名称'),
    sa.Column('type', sa.Integer(), nullable=False, comment='MCP 类型(0:stdio 1:sse)'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='远程 SSE 地址'),
    sa.Column('command', sa.String(length=255), nullable=True, comment='MCP 命令'),
    sa.Column('args', sa.String(length=255), nullable=True, comment='MCP 命令参数'),
    sa.Column('env', sa.JSON(), nullable=True, comment='MCP 环境变量'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='MCP 服务器表'
    )
    op.create_index(op.f('ix_app_ai_mcp_created_id'), 'app_ai_mcp', ['created_id'], unique=False)
    op.create_index(op.f('ix_app_ai_mcp_created_time'), 'app_ai_mcp', ['created_time'], unique=False)
    op.create_index(op.f('ix_app_ai_mcp_id'), 'app_ai_mcp', ['id'], unique=False)
    op.create_index(op.f('ix_app_ai_mcp_status'), 'app_ai_mcp', ['status'], unique=False)
    op.create_index(op.f('ix_app_ai_mcp_updated_id'), 'app_ai_mcp', ['updated_id'], unique=False)
    op.create_index(op.f('ix_app_ai_mcp_updated_time'), 'app_ai_mcp', ['updated_time'], unique=False)
    op.create_index(op.f('ix_app_ai_mcp_uuid'), 'app_ai_mcp', ['uuid'], unique=True)
    op.create_table('app_job',
    sa.Column('name', sa.String(length=64), nullable=True, comment='任务名称'),
    sa.Column('jobstore', sa.String(length=64), nullable=True, comment='存储器'),
    sa.Column('executor', sa.String(length=64), nullable=True, comment='执行器:将运行此作业的执行程序的名称'),
    sa.Column('trigger', sa.String(length=64), nullable=False, comment='触发器:控制此作业计划的 trigger 对象'),
    sa.Column('trigger_args', sa.Text(), nullable=True, comment='触发器参数'),
    sa.Column('func', sa.Text(), nullable=False, comment='任务函数'),
    sa.Column('args', sa.Text(), nullable=True, comment='位置参数'),
    sa.Column('kwargs', sa.Text(), nullable=True, comment='关键字参数'),
    sa.Column('coalesce', sa.Boolean(), nullable=True, comment='是否合并运行:是否在多个运行时间到期时仅运行作业一次'),
    sa.Column('max_instances', sa.Integer(), nullable=True, comment='最大实例数:允许的最大并发执行实例数'),
    sa.Column('start_date', sa.String(length=64), nullable=True, comment='开始时间'),
    sa.Column('end_date', sa.String(length=64), nullable=True, comment='结束时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='定时任务调度表'
    )
    op.create_index(op.f('ix_app_job_created_id'), 'app_job', ['created_id'], unique=False)
    op.create_index(op.f('ix_app_job_created_time'), 'app_job', ['created_time'], unique=False)
    op.create_index(op.f('ix_app_job_id'), 'app_job', ['id'], unique=False)
    op.create_index(op.f('ix_app_job_status'), 'app_job', ['status'], unique=False)
    op.create_index(op.f('ix_app_job_updated_id'), 'app_job', ['updated_id'], unique=False)
    op.create_index(op.f('ix_app_job_updated_time'), 'app_job', ['updated_time'], unique=False)
    op.create_index(op.f('ix_app_job_uuid'), 'app_job', ['uuid'], unique=True)
    op.create_table('app_myapp',
    sa.Column('name', sa.String(length=64), nullable=False, comment='应用名称'),
    sa.Column('access_url', sa.String(length=500), nullable=False, comment='访问地址'),
    sa.Column('icon_url', sa.String(length=300), nullable=True, comment='应用图标URL'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='应用系统表'
    )
    op.create_index(op.f('ix_app_myapp_created_id'), 'app_myapp', ['created_id'], unique=False)
    op.create_index(op.f('ix_app_myapp_created_time'), 'app_myapp', ['created_time'], unique=False)
    op.create_index(op.f('ix_app_myapp_id'), 'app_myapp', ['id'], unique=False)
    op.create_index(op.f('ix_app_myapp_status'), 'app_myapp', ['status'], unique=False)
    op.create_index(op.f('ix_app_myapp_updated_id'), 'app_myapp', ['updated_id'], unique=False)
    op.create_index(op.f('ix_app_myapp_updated_time'), 'app_myapp', ['updated_time'], unique=False)
    op.create_index(op.f('ix_app_myapp_uuid'), 'app_myapp', ['uuid'], unique=True)
    op.create_table('gen_demo',
    sa.Column('name', sa.String(length=64), nullable=False, comment='名称'),
    sa.Column('a', sa.Integer(), nullable=True, comment='整数'),
    sa.Column('b', sa.BIGINT(), nullable=True, comment='大整数'),
    sa.Column('c', sa.Float(), nullable=True, comment='浮点数'),
    sa.Column('d', sa.Boolean(), nullable=False, comment='布尔型'),
    sa.Column('e', sa.Date(), nullable=True, comment='日期'),
    sa.Column('f', sa.Time(), nullable=True, comment='时间'),
    sa.Column('g', sa.DateTime(), nullable=True, comment='日期时间'),
    sa.Column('h', sa.Text(), nullable=True, comment='长文本'),
    sa.Column('i', sa.JSON(), nullable=True, comment='元数据(JSON格式)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='示例表'
    )
    op.create_index(op.f('ix_gen_demo_created_id'), 'gen_demo', ['created_id'], unique=False)
    op.create_index(op.f('ix_gen_demo_created_time'), 'gen_demo', ['created_time'], unique=False)
    op.create_index(op.f('ix_gen_demo_id'), 'gen_demo', ['id'], unique=False)
    op.create_index(op.f('ix_gen_demo_status'), 'gen_demo', ['status'], unique=False)
    op.create_index(op.f('ix_gen_demo_updated_id'), 'gen_demo', ['updated_id'], unique=False)
    op.create_index(op.f('ix_gen_demo_updated_time'), 'gen_demo', ['updated_time'], unique=False)
    op.create_index(op.f('ix_gen_demo_uuid'), 'gen_demo', ['uuid'], unique=True)
    op.create_table('gen_table',
    sa.Column('table_name', sa.String(length=200), nullable=False, comment='表名称'),
    sa.Column('table_comment', sa.String(length=500), nullable=True, comment='表描述'),
    sa.Column('class_name', sa.String(length=100), nullable=False, comment='实体类名称'),
    sa.Column('package_name', sa.String(length=100), nullable=True, comment='生成包路径'),
    sa.Column('module_name', sa.String(length=30), nullable=True, comment='生成模块名'),
    sa.Column('business_name', sa.String(length=30), nullable=True, comment='生成业务名'),
    sa.Column('function_name', sa.String(length=100), nullable=True, comment='生成功能名'),
    sa.Column('sub_table_name', sa.String(length=64), nullable=True, comment='关联子表的表名'),
    sa.Column('sub_table_fk_name', sa.String(length=64), nullable=True, comment='子表关联的外键名'),
    sa.Column('parent_menu_id', sa.Integer(), nullable=True, comment='父菜单ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='代码生成表'
    )
    op.create_index(op.f('ix_gen_table_created_id'), 'gen_table', ['created_id'], unique=False)
    op.create_index(op.f('ix_gen_table_created_time'), 'gen_table', ['created_time'], unique=False)
    op.create_index(op.f('ix_gen_table_id'), 'gen_table', ['id'], unique=False)
    op.create_index(op.f('ix_gen_table_status'), 'gen_table', ['status'], unique=False)
    op.create_index(op.f('ix_gen_table_updated_id'), 'gen_table', ['updated_id'], unique=False)
    op.create_index(op.f('ix_gen_table_updated_time'), 'gen_table', ['updated_time'], unique=False)
    op.create_index(op.f('ix_gen_table_uuid'), 'gen_table', ['uuid'], unique=True)
    op.create_table('sys_dict_data',
    sa.Column('dict_sort', sa.Integer(), nullable=False, comment='字典排序'),
    sa.Column('dict_label', sa.String(length=255), nullable=False, comment='字典标签'),
    sa.Column('dict_value', sa.String(length=255), nullable=False, comment='字典键值'),
    sa.Column('css_class', sa.String(length=255), nullable=True, comment='样式属性（其他样式扩展）'),
    sa.Column('list_class', sa.String(length=255), nullable=True, comment='表格回显样式'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认（True是 False否）'),
    sa.Column('dict_type', sa.String(length=255), nullable=False, comment='字典类型'),
    sa.Column('dict_type_id', sa.Integer(), nullable=False, comment='字典类型ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['dict_type_id'], ['sys_dict_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典数据表'
    )
    op.create_index(op.f('ix_sys_dict_data_created_time'), 'sys_dict_data', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_id'), 'sys_dict_data', ['id'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_status'), 'sys_dict_data', ['status'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_updated_time'), 'sys_dict_data', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_uuid'), 'sys_dict_data', ['uuid'], unique=True)
    op.create_table('sys_log',
    sa.Column('type', sa.Integer(), nullable=False, comment='日志类型(1登录日志 2操作日志)'),
    sa.Column('request_path', sa.String(length=255), nullable=False, comment='请求路径'),
    sa.Column('request_method', sa.String(length=10), nullable=False, comment='请求方式'),
    sa.Column('request_payload', sa.Text(), nullable=True, comment='请求体'),
    sa.Column('request_ip', sa.String(length=50), nullable=True, comment='请求IP地址'),
    sa.Column('login_location', sa.String(length=255), nullable=True, comment='登录位置'),
    sa.Column('request_os', sa.String(length=64), nullable=True, comment='操作系统'),
    sa.Column('request_browser', sa.String(length=64), nullable=True, comment='浏览器'),
    sa.Column('response_code', sa.Integer(), nullable=False, comment='响应状态码'),
    sa.Column('response_json', sa.Text(), nullable=True, comment='响应体'),
    sa.Column('process_time', sa.String(length=20), nullable=True, comment='处理时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统日志表'
    )
    op.create_index(op.f('ix_sys_log_created_id'), 'sys_log', ['created_id'], unique=False)
    op.create_index(op.f('ix_sys_log_created_time'), 'sys_log', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_log_id'), 'sys_log', ['id'], unique=False)
    op.create_index(op.f('ix_sys_log_status'), 'sys_log', ['status'], unique=False)
    op.create_index(op.f('ix_sys_log_updated_id'), 'sys_log', ['updated_id'], unique=False)
    op.create_index(op.f('ix_sys_log_updated_time'), 'sys_log', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_log_uuid'), 'sys_log', ['uuid'], unique=True)
    op.create_table('sys_notice',
    sa.Column('notice_title', sa.String(length=64), nullable=False, comment='公告标题'),
    sa.Column('notice_type', sa.String(length=1), nullable=False, comment='公告类型(1通知 2公告)'),
    sa.Column('notice_content', sa.Text(), nullable=True, comment='公告内容'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='通知公告表'
    )
    op.create_index(op.f('ix_sys_notice_created_id'), 'sys_notice', ['created_id'], unique=False)
    op.create_index(op.f('ix_sys_notice_created_time'), 'sys_notice', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_notice_id'), 'sys_notice', ['id'], unique=False)
    op.create_index(op.f('ix_sys_notice_status'), 'sys_notice', ['status'], unique=False)
    op.create_index(op.f('ix_sys_notice_updated_id'), 'sys_notice', ['updated_id'], unique=False)
    op.create_index(op.f('ix_sys_notice_updated_time'), 'sys_notice', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_notice_uuid'), 'sys_notice', ['uuid'], unique=True)
    op.create_table('sys_position',
    sa.Column('name', sa.String(length=64), nullable=False, comment='岗位名称'),
    sa.Column('order', sa.Integer(), nullable=False, comment='显示排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='岗位表'
    )
    op.create_index(op.f('ix_sys_position_created_id'), 'sys_position', ['created_id'], unique=False)
    op.create_index(op.f('ix_sys_position_created_time'), 'sys_position', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_position_id'), 'sys_position', ['id'], unique=False)
    op.create_index(op.f('ix_sys_position_status'), 'sys_position', ['status'], unique=False)
    op.create_index(op.f('ix_sys_position_updated_id'), 'sys_position', ['updated_id'], unique=False)
    op.create_index(op.f('ix_sys_position_updated_time'), 'sys_position', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_position_uuid'), 'sys_position', ['uuid'], unique=True)
    op.create_table('sys_role_depts',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('dept_id', sa.Integer(), nullable=False, comment='部门ID'),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'dept_id'),
    comment='角色部门关联表'
    )
    op.create_table('sys_role_menus',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='菜单ID'),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    comment='角色菜单关联表'
    )
    op.create_table('sys_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户角色关联表'
    )
    op.create_table('app_job_log',
    sa.Column('job_name', sa.String(length=64), nullable=False, comment='任务名称'),
    sa.Column('job_group', sa.String(length=64), nullable=False, comment='任务组名'),
    sa.Column('job_executor', sa.String(length=64), nullable=False, comment='任务执行器'),
    sa.Column('invoke_target', sa.String(length=500), nullable=False, comment='调用目标字符串'),
    sa.Column('job_args', sa.String(length=255), nullable=True, comment='位置参数'),
    sa.Column('job_kwargs', sa.String(length=255), nullable=True, comment='关键字参数'),
    sa.Column('job_trigger', sa.String(length=255), nullable=True, comment='任务触发器'),
    sa.Column('job_message', sa.String(length=500), nullable=True, comment='日志信息'),
    sa.Column('exception_info', sa.String(length=2000), nullable=True, comment='异常信息'),
    sa.Column('job_id', sa.Integer(), nullable=True, comment='任务ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['job_id'], ['app_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='定时任务调度日志表'
    )
    op.create_index(op.f('ix_app_job_log_created_time'), 'app_job_log', ['created_time'], unique=False)
    op.create_index(op.f('ix_app_job_log_id'), 'app_job_log', ['id'], unique=False)
    op.create_index(op.f('ix_app_job_log_job_id'), 'app_job_log', ['job_id'], unique=False)
    op.create_index(op.f('ix_app_job_log_status'), 'app_job_log', ['status'], unique=False)
    op.create_index(op.f('ix_app_job_log_updated_time'), 'app_job_log', ['updated_time'], unique=False)
    op.create_index(op.f('ix_app_job_log_uuid'), 'app_job_log', ['uuid'], unique=True)
    op.create_table('gen_table_column',
    sa.Column('column_name', sa.String(length=200), nullable=False, comment='列名称'),
    sa.Column('column_comment', sa.String(length=500), nullable=True, comment='列描述'),
    sa.Column('column_type', sa.String(length=100), nullable=False, comment='列类型'),
    sa.Column('column_length', sa.String(length=50), nullable=True, comment='列长度'),
    sa.Column('column_default', sa.String(length=200), nullable=True, comment='列默认值'),
    sa.Column('is_pk', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否主键'),
    sa.Column('is_increment', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否自增'),
    sa.Column('is_nullable', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否允许为空'),
    sa.Column('is_unique', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否唯一'),
    sa.Column('python_type', sa.String(length=100), nullable=True, comment='Python类型'),
    sa.Column('python_field', sa.String(length=200), nullable=True, comment='Python字段名'),
    sa.Column('is_insert', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否为新增字段'),
    sa.Column('is_edit', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否编辑字段'),
    sa.Column('is_list', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否列表字段'),
    sa.Column('is_query', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否查询字段'),
    sa.Column('query_type', sa.String(length=50), nullable=True, comment='查询方式'),
    sa.Column('html_type', sa.String(length=100), nullable=True, comment='显示类型'),
    sa.Column('dict_type', sa.String(length=200), nullable=True, comment='字典类型'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('table_id', sa.Integer(), nullable=False, comment='归属表编号'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='是否启用(0:启用 1:禁用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['gen_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='代码生成表字段'
    )
    op.create_index(op.f('ix_gen_table_column_created_id'), 'gen_table_column', ['created_id'], unique=False)
    op.create_index(op.f('ix_gen_table_column_created_time'), 'gen_table_column', ['created_time'], unique=False)
    op.create_index(op.f('ix_gen_table_column_id'), 'gen_table_column', ['id'], unique=False)
    op.create_index(op.f('ix_gen_table_column_status'), 'gen_table_column', ['status'], unique=False)
    op.create_index(op.f('ix_gen_table_column_table_id'), 'gen_table_column', ['table_id'], unique=False)
    op.create_index(op.f('ix_gen_table_column_updated_id'), 'gen_table_column', ['updated_id'], unique=False)
    op.create_index(op.f('ix_gen_table_column_updated_time'), 'gen_table_column', ['updated_time'], unique=False)
    op.create_index(op.f('ix_gen_table_column_uuid'), 'gen_table_column', ['uuid'], unique=True)
    op.create_table('sys_user_positions',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('position_id', sa.Integer(), nullable=False, comment='岗位ID'),
    sa.ForeignKeyConstraint(['position_id'], ['sys_position.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'position_id'),
    comment='用户岗位关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_positions')
    op.drop_index(op.f('ix_gen_table_column_uuid'), table_name='gen_table_column')
    op.drop_index(op.f('ix_gen_table_column_updated_time'), table_name='gen_table_column')
    op.drop_index(op.f('ix_gen_table_column_updated_id'), table_name='gen_table_column')
    op.drop_index(op.f('ix_gen_table_column_table_id'), table_name='gen_table_column')
    op.drop_index(op.f('ix_gen_table_column_status'), table_name='gen_table_column')
    op.drop_index(op.f('ix_gen_table_column_id'), table_name='gen_table_column')
    op.drop_index(op.f('ix_gen_table_column_created_time'), table_name='gen_table_column')
    op.drop_index(op.f('ix_gen_table_column_created_id'), table_name='gen_table_column')
    op.drop_table('gen_table_column')
    op.drop_index(op.f('ix_app_job_log_uuid'), table_name='app_job_log')
    op.drop_index(op.f('ix_app_job_log_updated_time'), table_name='app_job_log')
    op.drop_index(op.f('ix_app_job_log_status'), table_name='app_job_log')
    op.drop_index(op.f('ix_app_job_log_job_id'), table_name='app_job_log')
    op.drop_index(op.f('ix_app_job_log_id'), table_name='app_job_log')
    op.drop_index(op.f('ix_app_job_log_created_time'), table_name='app_job_log')
    op.drop_table('app_job_log')
    op.drop_table('sys_user_roles')
    op.drop_table('sys_role_menus')
    op.drop_table('sys_role_depts')
    op.drop_index(op.f('ix_sys_position_uuid'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_updated_time'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_updated_id'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_status'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_id'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_created_time'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_created_id'), table_name='sys_position')
    op.drop_table('sys_position')
    op.drop_index(op.f('ix_sys_notice_uuid'), table_name='sys_notice')
    op.drop_index(op.f('ix_sys_notice_updated_time'), table_name='sys_notice')
    op.drop_index(op.f('ix_sys_notice_updated_id'), table_name='sys_notice')
    op.drop_index(op.f('ix_sys_notice_status'), table_name='sys_notice')
    op.drop_index(op.f('ix_sys_notice_id'), table_name='sys_notice')
    op.drop_index(op.f('ix_sys_notice_created_time'), table_name='sys_notice')
    op.drop_index(op.f('ix_sys_notice_created_id'), table_name='sys_notice')
    op.drop_table('sys_notice')
    op.drop_index(op.f('ix_sys_log_uuid'), table_name='sys_log')
    op.drop_index(op.f('ix_sys_log_updated_time'), table_name='sys_log')
    op.drop_index(op.f('ix_sys_log_updated_id'), table_name='sys_log')
    op.drop_index(op.f('ix_sys_log_status'), table_name='sys_log')
    op.drop_index(op.f('ix_sys_log_id'), table_name='sys_log')
    op.drop_index(op.f('ix_sys_log_created_time'), table_name='sys_log')
    op.drop_index(op.f('ix_sys_log_created_id'), table_name='sys_log')
    op.drop_table('sys_log')
    op.drop_index(op.f('ix_sys_dict_data_uuid'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_updated_time'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_status'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_id'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_created_time'), table_name='sys_dict_data')
    op.drop_table('sys_dict_data')
    op.drop_index(op.f('ix_gen_table_uuid'), table_name='gen_table')
    op.drop_index(op.f('ix_gen_table_updated_time'), table_name='gen_table')
    op.drop_index(op.f('ix_gen_table_updated_id'), table_name='gen_table')
    op.drop_index(op.f('ix_gen_table_status'), table_name='gen_table')
    op.drop_index(op.f('ix_gen_table_id'), table_name='gen_table')
    op.drop_index(op.f('ix_gen_table_created_time'), table_name='gen_table')
    op.drop_index(op.f('ix_gen_table_created_id'), table_name='gen_table')
    op.drop_table('gen_table')
    op.drop_index(op.f('ix_gen_demo_uuid'), table_name='gen_demo')
    op.drop_index(op.f('ix_gen_demo_updated_time'), table_name='gen_demo')
    op.drop_index(op.f('ix_gen_demo_updated_id'), table_name='gen_demo')
    op.drop_index(op.f('ix_gen_demo_status'), table_name='gen_demo')
    op.drop_index(op.f('ix_gen_demo_id'), table_name='gen_demo')
    op.drop_index(op.f('ix_gen_demo_created_time'), table_name='gen_demo')
    op.drop_index(op.f('ix_gen_demo_created_id'), table_name='gen_demo')
    op.drop_table('gen_demo')
    op.drop_index(op.f('ix_app_myapp_uuid'), table_name='app_myapp')
    op.drop_index(op.f('ix_app_myapp_updated_time'), table_name='app_myapp')
    op.drop_index(op.f('ix_app_myapp_updated_id'), table_name='app_myapp')
    op.drop_index(op.f('ix_app_myapp_status'), table_name='app_myapp')
    op.drop_index(op.f('ix_app_myapp_id'), table_name='app_myapp')
    op.drop_index(op.f('ix_app_myapp_created_time'), table_name='app_myapp')
    op.drop_index(op.f('ix_app_myapp_created_id'), table_name='app_myapp')
    op.drop_table('app_myapp')
    op.drop_index(op.f('ix_app_job_uuid'), table_name='app_job')
    op.drop_index(op.f('ix_app_job_updated_time'), table_name='app_job')
    op.drop_index(op.f('ix_app_job_updated_id'), table_name='app_job')
    op.drop_index(op.f('ix_app_job_status'), table_name='app_job')
    op.drop_index(op.f('ix_app_job_id'), table_name='app_job')
    op.drop_index(op.f('ix_app_job_created_time'), table_name='app_job')
    op.drop_index(op.f('ix_app_job_created_id'), table_name='app_job')
    op.drop_table('app_job')
    op.drop_index(op.f('ix_app_ai_mcp_uuid'), table_name='app_ai_mcp')
    op.drop_index(op.f('ix_app_ai_mcp_updated_time'), table_name='app_ai_mcp')
    op.drop_index(op.f('ix_app_ai_mcp_updated_id'), table_name='app_ai_mcp')
    op.drop_index(op.f('ix_app_ai_mcp_status'), table_name='app_ai_mcp')
    op.drop_index(op.f('ix_app_ai_mcp_id'), table_name='app_ai_mcp')
    op.drop_index(op.f('ix_app_ai_mcp_created_time'), table_name='app_ai_mcp')
    op.drop_index(op.f('ix_app_ai_mcp_created_id'), table_name='app_ai_mcp')
    op.drop_table('app_ai_mcp')
    op.drop_index(op.f('ix_sys_user_uuid'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_updated_time'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_updated_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_dept_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_created_time'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_created_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_uuid'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_updated_time'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_status'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_created_time'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_code'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_param_uuid'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_updated_time'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_status'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_id'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_created_time'), table_name='sys_param')
    op.drop_table('sys_param')
    op.drop_index(op.f('ix_sys_menu_uuid'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_updated_time'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_status'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_parent_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_created_time'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_dict_type_uuid'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_updated_time'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_status'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_id'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_created_time'), table_name='sys_dict_type')
    op.drop_table('sys_dict_type')
    op.drop_index(op.f('ix_sys_dept_uuid'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_updated_time'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_updated_id'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_status'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_parent_id'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_id'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_created_time'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_created_id'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_code'), table_name='sys_dept')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
